//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment2_T.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MyHospital", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class MyHospital : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LicenseField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string License {
            get {
                return this.LicenseField;
            }
            set {
                if ((object.ReferenceEquals(this.LicenseField, value) != true)) {
                    this.LicenseField = value;
                    this.RaisePropertyChanged("License");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MyDoctor", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class MyDoctor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        private int IDField;
        
        private int GenderField;
        
        private System.DateTime dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LicenseField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((this.GenderField.Equals(value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime date {
            get {
                return this.dateField;
            }
            set {
                if ((this.dateField.Equals(value) != true)) {
                    this.dateField = value;
                    this.RaisePropertyChanged("date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string License {
            get {
                return this.LicenseField;
            }
            set {
                if ((object.ReferenceEquals(this.LicenseField, value) != true)) {
                    this.LicenseField = value;
                    this.RaisePropertyChanged("License");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.AssiServiceSoap")]
    public interface AssiServiceSoap {
        
        // CODEGEN: Generating message contract since element name checkResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/check", ReplyAction="*")]
        Assignment2_T.ServiceReference.checkResponse check(Assignment2_T.ServiceReference.checkRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/check", ReplyAction="*")]
        System.Threading.Tasks.Task<Assignment2_T.ServiceReference.checkResponse> checkAsync(Assignment2_T.ServiceReference.checkRequest request);
        
        // CODEGEN: Generating message contract since element name reutrnHosResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/reutrnHos", ReplyAction="*")]
        Assignment2_T.ServiceReference.reutrnHosResponse reutrnHos(Assignment2_T.ServiceReference.reutrnHosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/reutrnHos", ReplyAction="*")]
        System.Threading.Tasks.Task<Assignment2_T.ServiceReference.reutrnHosResponse> reutrnHosAsync(Assignment2_T.ServiceReference.reutrnHosRequest request);
        
        // CODEGEN: Generating message contract since element name reutrnDocResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/reutrnDoc", ReplyAction="*")]
        Assignment2_T.ServiceReference.reutrnDocResponse reutrnDoc(Assignment2_T.ServiceReference.reutrnDocRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/reutrnDoc", ReplyAction="*")]
        System.Threading.Tasks.Task<Assignment2_T.ServiceReference.reutrnDocResponse> reutrnDocAsync(Assignment2_T.ServiceReference.reutrnDocRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class checkRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="check", Namespace="http://tempuri.org/", Order=0)]
        public Assignment2_T.ServiceReference.checkRequestBody Body;
        
        public checkRequest() {
        }
        
        public checkRequest(Assignment2_T.ServiceReference.checkRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class checkRequestBody {
        
        public checkRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class checkResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="checkResponse", Namespace="http://tempuri.org/", Order=0)]
        public Assignment2_T.ServiceReference.checkResponseBody Body;
        
        public checkResponse() {
        }
        
        public checkResponse(Assignment2_T.ServiceReference.checkResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class checkResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string checkResult;
        
        public checkResponseBody() {
        }
        
        public checkResponseBody(string checkResult) {
            this.checkResult = checkResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class reutrnHosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="reutrnHos", Namespace="http://tempuri.org/", Order=0)]
        public Assignment2_T.ServiceReference.reutrnHosRequestBody Body;
        
        public reutrnHosRequest() {
        }
        
        public reutrnHosRequest(Assignment2_T.ServiceReference.reutrnHosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class reutrnHosRequestBody {
        
        public reutrnHosRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class reutrnHosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="reutrnHosResponse", Namespace="http://tempuri.org/", Order=0)]
        public Assignment2_T.ServiceReference.reutrnHosResponseBody Body;
        
        public reutrnHosResponse() {
        }
        
        public reutrnHosResponse(Assignment2_T.ServiceReference.reutrnHosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class reutrnHosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Assignment2_T.ServiceReference.MyHospital[] reutrnHosResult;
        
        public reutrnHosResponseBody() {
        }
        
        public reutrnHosResponseBody(Assignment2_T.ServiceReference.MyHospital[] reutrnHosResult) {
            this.reutrnHosResult = reutrnHosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class reutrnDocRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="reutrnDoc", Namespace="http://tempuri.org/", Order=0)]
        public Assignment2_T.ServiceReference.reutrnDocRequestBody Body;
        
        public reutrnDocRequest() {
        }
        
        public reutrnDocRequest(Assignment2_T.ServiceReference.reutrnDocRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class reutrnDocRequestBody {
        
        public reutrnDocRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class reutrnDocResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="reutrnDocResponse", Namespace="http://tempuri.org/", Order=0)]
        public Assignment2_T.ServiceReference.reutrnDocResponseBody Body;
        
        public reutrnDocResponse() {
        }
        
        public reutrnDocResponse(Assignment2_T.ServiceReference.reutrnDocResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class reutrnDocResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Assignment2_T.ServiceReference.MyDoctor[] reutrnDocResult;
        
        public reutrnDocResponseBody() {
        }
        
        public reutrnDocResponseBody(Assignment2_T.ServiceReference.MyDoctor[] reutrnDocResult) {
            this.reutrnDocResult = reutrnDocResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AssiServiceSoapChannel : Assignment2_T.ServiceReference.AssiServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AssiServiceSoapClient : System.ServiceModel.ClientBase<Assignment2_T.ServiceReference.AssiServiceSoap>, Assignment2_T.ServiceReference.AssiServiceSoap {
        
        public AssiServiceSoapClient() {
        }
        
        public AssiServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AssiServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AssiServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AssiServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Assignment2_T.ServiceReference.checkResponse Assignment2_T.ServiceReference.AssiServiceSoap.check(Assignment2_T.ServiceReference.checkRequest request) {
            return base.Channel.check(request);
        }
        
        public string check() {
            Assignment2_T.ServiceReference.checkRequest inValue = new Assignment2_T.ServiceReference.checkRequest();
            inValue.Body = new Assignment2_T.ServiceReference.checkRequestBody();
            Assignment2_T.ServiceReference.checkResponse retVal = ((Assignment2_T.ServiceReference.AssiServiceSoap)(this)).check(inValue);
            return retVal.Body.checkResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Assignment2_T.ServiceReference.checkResponse> Assignment2_T.ServiceReference.AssiServiceSoap.checkAsync(Assignment2_T.ServiceReference.checkRequest request) {
            return base.Channel.checkAsync(request);
        }
        
        public System.Threading.Tasks.Task<Assignment2_T.ServiceReference.checkResponse> checkAsync() {
            Assignment2_T.ServiceReference.checkRequest inValue = new Assignment2_T.ServiceReference.checkRequest();
            inValue.Body = new Assignment2_T.ServiceReference.checkRequestBody();
            return ((Assignment2_T.ServiceReference.AssiServiceSoap)(this)).checkAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Assignment2_T.ServiceReference.reutrnHosResponse Assignment2_T.ServiceReference.AssiServiceSoap.reutrnHos(Assignment2_T.ServiceReference.reutrnHosRequest request) {
            return base.Channel.reutrnHos(request);
        }
        
        public Assignment2_T.ServiceReference.MyHospital[] reutrnHos() {
            Assignment2_T.ServiceReference.reutrnHosRequest inValue = new Assignment2_T.ServiceReference.reutrnHosRequest();
            inValue.Body = new Assignment2_T.ServiceReference.reutrnHosRequestBody();
            Assignment2_T.ServiceReference.reutrnHosResponse retVal = ((Assignment2_T.ServiceReference.AssiServiceSoap)(this)).reutrnHos(inValue);
            return retVal.Body.reutrnHosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Assignment2_T.ServiceReference.reutrnHosResponse> Assignment2_T.ServiceReference.AssiServiceSoap.reutrnHosAsync(Assignment2_T.ServiceReference.reutrnHosRequest request) {
            return base.Channel.reutrnHosAsync(request);
        }
        
        public System.Threading.Tasks.Task<Assignment2_T.ServiceReference.reutrnHosResponse> reutrnHosAsync() {
            Assignment2_T.ServiceReference.reutrnHosRequest inValue = new Assignment2_T.ServiceReference.reutrnHosRequest();
            inValue.Body = new Assignment2_T.ServiceReference.reutrnHosRequestBody();
            return ((Assignment2_T.ServiceReference.AssiServiceSoap)(this)).reutrnHosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Assignment2_T.ServiceReference.reutrnDocResponse Assignment2_T.ServiceReference.AssiServiceSoap.reutrnDoc(Assignment2_T.ServiceReference.reutrnDocRequest request) {
            return base.Channel.reutrnDoc(request);
        }
        
        public Assignment2_T.ServiceReference.MyDoctor[] reutrnDoc() {
            Assignment2_T.ServiceReference.reutrnDocRequest inValue = new Assignment2_T.ServiceReference.reutrnDocRequest();
            inValue.Body = new Assignment2_T.ServiceReference.reutrnDocRequestBody();
            Assignment2_T.ServiceReference.reutrnDocResponse retVal = ((Assignment2_T.ServiceReference.AssiServiceSoap)(this)).reutrnDoc(inValue);
            return retVal.Body.reutrnDocResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Assignment2_T.ServiceReference.reutrnDocResponse> Assignment2_T.ServiceReference.AssiServiceSoap.reutrnDocAsync(Assignment2_T.ServiceReference.reutrnDocRequest request) {
            return base.Channel.reutrnDocAsync(request);
        }
        
        public System.Threading.Tasks.Task<Assignment2_T.ServiceReference.reutrnDocResponse> reutrnDocAsync() {
            Assignment2_T.ServiceReference.reutrnDocRequest inValue = new Assignment2_T.ServiceReference.reutrnDocRequest();
            inValue.Body = new Assignment2_T.ServiceReference.reutrnDocRequestBody();
            return ((Assignment2_T.ServiceReference.AssiServiceSoap)(this)).reutrnDocAsync(inValue);
        }
    }
}
